# Generated by Django 4.2.3 on 2024-03-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_order_deposit_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('payment_period', models.IntegerField(verbose_name='In months length of payment period')),
                ('deposit', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deposit',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='order',
            name='contract_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_progress',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.paymentmethod'),
        ),
    ]
