# Generated by Django 4.2.3 on 2024-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_extra_data_alter_order_payment_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.FileField(upload_to='static/course_videos'),
        ),
    ]
