# Generated by Django 4.2.3 on 2024-03-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_paymentstory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentStory',
            new_name='PaymentHistory',
        ),
    ]
