# Generated by Django 4.2.3 on 2024-03-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_paymentstory_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='static/course_videos'),
        ),
    ]
