# Generated by Django 4.2.3 on 2024-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate_percentage',
        ),
    ]
