# Generated by Django 4.2.3 on 2024-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_paymentmethod_extra_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='extra_payment_rate',
            field=models.IntegerField(default=0),
        ),
    ]
