# Generated by Django 4.2.3 on 2024-03-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_paymentmethod_extra_payment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
