# Generated by Django 4.2.3 on 2024-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_rate_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
