# Generated by Django 4.2.3 on 2024-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_order_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_progress',
            field=models.IntegerField(default=0),
        ),
    ]
