# Generated by Django 4.2.3 on 2024-04-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_order_creator_alter_order_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-time_create']},
        ),
    ]
