# Generated by Django 4.2.3 on 2024-02-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='related_admin',
            new_name='related_staff',
        ),
    ]
