# Generated by Django 4.2.3 on 2024-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_analizer',
            field=models.BooleanField(default=False, verbose_name='analyzer admin status'),
        ),
    ]
