# Generated by Django 4.2.3 on 2024-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
