# Generated by Django 4.2.3 on 2024-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_last_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
